export const GET_MUSIC_REDORD_REQUEST = "GET_MUSIC_REDORD_REQUEST";
export const GET_MUSIC_REDORD_SUCCESS = "GET_MUSIC_REDORD_SUCCESS";
export const GET_MUSIC_REDORD_FAILURE = "GET_MUSIC_REDORD_FAILURE";

export const UPDATE_MUSIC_REDORD_REQUEST = "UPDATE_MUSIC_REDORD_REQUEST";
export const UPDATE_MUSIC_REDORD_SUCCESS = "UPDATE_MUSIC_REDORD_SUCCESS";
export const UPDATE_MUSIC_REDORD_FAILURE = "UPDATE_MUSIC_REDORD_FAILURE";
